name: docker helper
on: [push, pull_request]
permissions: read-all
jobs:
  test:
    name: docker helper â€” ${{ matrix.label }}
    strategy:
      matrix:
        include:
          - { base_image: arm32v7/alpine, platform: linux/arm/v7, label: armv7 }
          - { base_image: arm64v8/alpine, platform: linux/arm64/v8, label: arm64 }
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker buildx build --platform ${{ matrix.platform }} --load -t downloader - << EOF
          FROM ${{ matrix.base_image }}
          WORKDIR /app
          RUN apk update && apk add curl
          CMD ["sh", "posix_helper.sh"]
          EOF
      - name: Run Docker container
        run: docker run --rm --platform ${{ matrix.platform }} -v ${{ github.workspace }}:/app -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} downloader
      - name: Unarchive the downloaded file
        run: |
          archive_name=$(ls stockfish-*.tar 2>/dev/null)
          tar -xvf $archive_name
          binary_name="${archive_name%.tar}"
          echo "binary_name=$binary_name" >> $GITHUB_ENV
      - name: Run stockfish compiler
        run: ./stockfish/${{ env.binary_name }} compiler
